### ISSUE TITLE
ping4 using ipv6 address from DNS resolved hostname

### ISSUE THREAD

**Issue by lager1** [monitoring-plugins/monitoring-plugins#1550] opened 2018-09-25 11:19 UTC
_From @lager1 on September 25, 2018 9:53_

We discovered that monitoring plugin ping4 has quite strange behavior when the destination DNS name provides IPv6 addresses in form of AAAA DNS records but does not respond to ICMP over IPv6.

## Expected Behavior

When using ping4, the plugin should only use DNS A records when given a DNS hostname.

## Current Behavior

When used for "problematic" DNS record:

```
'/usr/lib/nagios/plugins/check_ping' '-4' '-H' 'er.zskunstat.cz' '-c' '2000,100%' '-w' '1500,60%'
PING CRITICAL - Packet loss = 100%|rta=2000.000000ms;1500.000000;2000.000000;0.000000 pl=100%;60;100;0 
``` 

tcpdump of this test:
```
tcpdump -n host 82.117.152.45 or host 2001:1a48:b:8000:1::20
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eno1, link-type EN10MB (Ethernet), capture size 262144 bytes
11:45:30.791150 IP6 2001:718:1:e::233:246 > 2001:1a48:b:8000:1::20: ICMP6, echo request, seq 1, length 64
11:45:31.814424 IP6 2001:718:1:e::233:246 > 2001:1a48:b:8000:1::20: ICMP6, echo request, seq 2, length 64
11:45:32.838417 IP6 2001:718:1:e::233:246 > 2001:1a48:b:8000:1::20: ICMP6, echo request, seq 3, length 64
11:45:33.862414 IP6 2001:718:1:e::233:246 > 2001:1a48:b:8000:1::20: ICMP6, echo request, seq 4, length 64
11:45:34.886426 IP6 2001:718:1:e::233:246 > 2001:1a48:b:8000:1::20: ICMP6, echo request, seq 5, length 64
11:45:35.914431 IP6 2001:718:1:e::233:246 > 2001:1a48:b:8000:1::20: ICMP6, echo request, seq 6, length 64
11:45:36.934426 IP6 2001:718:1:e::233:246 > 2001:1a48:b:8000:1::20: ICMP6, echo request, seq 7, length 64
11:45:37.958399 IP6 2001:718:1:e::233:246 > 2001:1a48:b:8000:1::20: ICMP6, echo request, seq 8, length 64
11:45:38.982429 IP6 2001:718:1:e::233:246 > 2001:1a48:b:8000:1::20: ICMP6, echo request, seq 9, length 64
11:45:40.006435 IP6 2001:718:1:e::233:246 > 2001:1a48:b:8000:1::20: ICMP6, echo request, seq 10, length 64
11:45:41.030436 IP6 2001:718:1:e::233:246 > 2001:1a48:b:8000:1::20: ICMP6, echo request, seq 11, length 64
11:45:42.054428 IP6 2001:718:1:e::233:246 > 2001:1a48:b:8000:1::20: ICMP6, echo request, seq 12, length 64
11:45:43.078423 IP6 2001:718:1:e::233:246 > 2001:1a48:b:8000:1::20: ICMP6, echo request, seq 13, length 64
11:45:44.102433 IP6 2001:718:1:e::233:246 > 2001:1a48:b:8000:1::20: ICMP6, echo request, seq 14, length 64
11:45:45.126422 IP6 2001:718:1:e::233:246 > 2001:1a48:b:8000:1::20: ICMP6, echo request, seq 15, length 64
```

The host er.zskunstat.cz does not respond to ping over IPv6, but it does over IPv4:

```
dig +short er.zskunstat.cz
82.117.152.45
'/usr/lib/nagios/plugins/check_ping' '-4' '-H' '82.117.152.45' '-c' '2000,100%' '-w' '1500,60%'
PING OK - Packet loss = 0%, RTA = 6.11 ms|rta=6.105000ms;1500.000000;2000.000000;0.000000 pl=0%;60;100;0 
``` 

## Steps to Reproduce (for bugs)

1. Add host to icinga2.
2. Create AAAA DNS record for it.
3. Set host to IPv4 only.
4. Run ping4 test against it.

## Your Environment

* Version used (`icinga2 --version`):
```
icinga2 - The Icinga 2 network monitoring daemon (version: r2.9.1-1)

Copyright (c) 2012-2018 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: Debian GNU/Linux
  Platform version: 9 (stretch)
  Kernel: Linux
  Kernel version: 4.9.0-8-amd64
  Architecture: x86_64

Build information:
  Compiler: GNU 6.3.0
  Build host: 83e7f59f33f0
```
* Operating System and version:
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.5 (stretch)
Release:	9.5
Codename:	stretch
```
* Enabled features (`icinga2 feature list`):
```
Disabled features: command compatlog debuglog elasticsearch gelf graphite influxdb livestatus opentsdb perfdata statusdata syslog
Enabled features: api checker ido-mysql mainlog notification
```
* Icinga Web 2 version and modules (System - About):
icingaweb2 2.6.1
director @ `3c02f7499fe06299af083cb723be236555efaf93`
monitoring 2.6.1
* Config validation (`icinga2 daemon -C`):
```
[2018-09-20 15:19:48 +0200] information/cli: Icinga application loader (version: r2.9.1-1)
[2018-09-20 15:19:48 +0200] information/cli: Loading configuration file(s).
[2018-09-20 15:19:49 +0200] information/ConfigItem: Committing config item(s).
[2018-09-20 15:19:49 +0200] information/ApiListener: My API identity: ermon.cesnet.cz
[2018-09-20 15:19:59 +0200] information/WorkQueue: #4 (DaemonUtility::LoadConfigFiles) items: 0, rate: 32.5833/s (1955/min 1955/5min 1955/15min);
[2018-09-20 15:19:59 +0200] information/WorkQueue: #5 (IdoMysqlConnection, ido-mysql) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2018-09-20 15:19:59 +0200] information/WorkQueue: #7 (ApiListener, SyncQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2018-09-20 15:19:59 +0200] information/WorkQueue: #6 (ApiListener, RelayQueue) items: 0, rate:  0/s (0/min 0/5min 0/15min);
[2018-09-20 15:20:06 +0200] warning/ApplyRule: Apply rule 'COMPROMISED-USERS-osmec.cz' (in /var/lib/icinga2/api/packages/director/906ca4bb-0a2c-45fb-9bf1-a3f4f6afdbdf/zones.d/director-global/service_apply_rules/static_config.conf: 64:5-64:60) for type 'Service' does not match anywhere!
[2018-09-20 15:20:06 +0200] warning/ApplyRule: Apply rule 'CONCURRENT-INST-osmec.cz' (in /var/lib/icinga2/api/packages/director/906ca4bb-0a2c-45fb-9bf1-a3f4f6afdbdf/zones.d/director-global/service_apply_rules/static_config.conf: 86:5-86:58) for type 'Service' does not match anywhere!
[2018-09-20 15:20:06 +0200] information/ConfigItem: Instantiated 45040 Services.
[2018-09-20 15:20:06 +0200] information/ConfigItem: Instantiated 239 ServiceGroups.
[2018-09-20 15:20:06 +0200] information/ConfigItem: Instantiated 225 HostGroups.
[2018-09-20 15:20:06 +0200] information/ConfigItem: Instantiated 1 FileLogger.
[2018-09-20 15:20:06 +0200] information/ConfigItem: Instantiated 1 NotificationComponent.
[2018-09-20 15:20:06 +0200] information/ConfigItem: Instantiated 2 NotificationCommands.
[2018-09-20 15:20:06 +0200] information/ConfigItem: Instantiated 45040 Notifications.
[2018-09-20 15:20:06 +0200] information/ConfigItem: Instantiated 1 IcingaApplication.
[2018-09-20 15:20:06 +0200] information/ConfigItem: Instantiated 236 Hosts.
[2018-09-20 15:20:06 +0200] information/ConfigItem: Instantiated 1 ApiListener.
[2018-09-20 15:20:06 +0200] information/ConfigItem: Instantiated 85619 Dependencies.
[2018-09-20 15:20:06 +0200] information/ConfigItem: Instantiated 1 Comment.
[2018-09-20 15:20:06 +0200] information/ConfigItem: Instantiated 1 CheckerComponent.
[2018-09-20 15:20:06 +0200] information/ConfigItem: Instantiated 4 Zones.
[2018-09-20 15:20:06 +0200] information/ConfigItem: Instantiated 2 Endpoints.
[2018-09-20 15:20:06 +0200] information/ConfigItem: Instantiated 2 ApiUsers.
[2018-09-20 15:20:06 +0200] information/ConfigItem: Instantiated 235 UserGroups.
[2018-09-20 15:20:06 +0200] information/ConfigItem: Instantiated 1 IdoMysqlConnection.
[2018-09-20 15:20:06 +0200] information/ConfigItem: Instantiated 229 CheckCommands.
[2018-09-20 15:20:06 +0200] information/ConfigItem: Instantiated 3 TimePeriods.
[2018-09-20 15:20:06 +0200] information/ConfigItem: Instantiated 311 Users.
[2018-09-20 15:20:06 +0200] information/ScriptGlobal: Dumping variables to file '/var/cache/icinga2/icinga2.vars'
[2018-09-20 15:20:06 +0200] information/cli: Finished validating the configuration file(s).
```

_Copied from original issue: Icinga/icinga2#6631_

**Comment by lager1** [comment] 2018-09-25 11:19
_From @dnsmichi on September 25, 2018 10:59_

`check_ping` isn't part of Icinga 2 itself, please head over to https://github.com/monitoring-plugins/monitoring-plugins .. Icinga 2 doesn't do any DNS resolving of check plugin parameters either.

**Comment by oskar456** [comment] 2018-10-01 12:30
I believe this is caused by the change of the behaviour of `ping` binary on Debian 9, which uses single binary to do both IPv4 and IPv6 pings. IPv4-only behaviour can be restored by passing `-4` switch to `ping` binary or calling `ping4` instead.

However such change would be incompatible with distros running other implementations of ping so there should be probably some configure-time detection.

**Comment by oskar456** [comment] 2018-10-01 12:44
Actually, there is an [open issue in Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=863981) for this. But this is not Debian specific as new IPv6-ready `ping` binary finds its way to many distros.

**Comment by stoecker** [comment] 2019-04-09 12:23
A simple fix for this issue - it ignores the fact, that older ping commands don't have a -4 option.

```
diff -ur monitoring-plugins-2.2/plugins/check_ping.c monitoring-plugins-2.2_fix/plugins/check_ping.c
--- monitoring-plugins-2.2/plugins/check_ping.c 2016-11-29 09:45:08.000000000 +0100
+++ monitoring-plugins-2.2_fix/plugins/check_ping.c     2019-04-09 14:09:57.574380368 +0200
@@ -128,6 +128,11 @@
 #else
                xasprintf (&cmd, rawcmd, addresses[i], max_packets);
 #endif
+               if (address_family == AF_INET) {
+                       free(rawcmd);
+                       rawcmd = cmd;
+                       xasprintf (&cmd, "%s -4", rawcmd);
+               }
 
                if (verbose >= 2)
                        printf ("CMD: %s\n", cmd);_

```

**Comment by L4rS6** [comment] 2019-06-11 10:15
Same problem here on Ubuntu 18.04.

**Comment by ghciv6** [comment] 2019-06-12 18:09
> A simple fix for this issue - it ignores the fact, that older ping commands don't have a -4 option.
> 

it's better to fix PING_COMMAND generated by configure. If ping doesn't accept a '-4' option.

**Comment by ghciv6** [comment] 2019-06-12 19:20
```
diff --git a/configure.ac b/configure.ac
index 08a0e78..2f5ca04 100644
--- a/configure.ac
+++ b/configure.ac
@@ -1064,6 +1064,15 @@ then
        ac_cv_ping_packets_first=yes
        AC_MSG_RESULT([$with_ping_command])
 
+elif $PATH_TO_PING -4 -n -U -w 10 -c 1 127.0.0.1 2>/dev/null | \
+       egrep -i "^round-trip|^rtt" >/dev/null
+then
+       # check if -4 is supported - issue #1550
+       with_ping_command="$PATH_TO_PING -4 -n -U -w %d -c %d %s"
+       ac_cv_ping_packets_first=yes
+       ac_cv_ping_has_timeout=yes
+       AC_MSG_RESULT([$with_ping_command])
+
 elif $PATH_TO_PING -n -U -w 10 -c 1 127.0.0.1 2>/dev/null | \
        egrep -i "^round-trip|^rtt" >/dev/null
 then
```

**Comment by L4rS6** [comment] 2020-04-09 12:18
Is there any reason that this fix doesn't get merged?

**Comment by ghciv6** [comment] 2020-04-12 16:54
- no one responded that the suggested fix works and
- no maintainer is looking into this issue?

**Comment by sni** [comment] 2020-04-13 14:51
Could you please turn this into a pull request so somebody could merge it?

**Comment by sni** [comment] 2020-04-14 10:37
thanks for you patience. I've merged the proposed fix.

**Closed by sni** 2020-04-14 10:37 UTC
