### ISSUE TITLE
[Mayhem] Crashes while passing garbage as argument [sf#3614674]

### ISSUE THREAD

**Issue by monitoring-user** [monitoring-plugins/monitoring-plugins#1147] opened 2013-09-24 15:05 UTC
Submitted by cyco_dd on 2013-07-11 18:01:50

The Mayhem[1] project tested all Debian binary packages if they can be crashed by passing garbage arguments. For nagios-plugins there was found a couple of bugs: 

http://bugs.debian.org/cgi-bin/pkgreport.cgi?src=nagios-plugins;dist=unstable;submitter=alexandre%40cmu.edu

Whould be nice to have those fixed, even if they are minor issues.

Many thanks, Jan.
[1] http://lists.debian.org/debian-devel/2013/06/msg00720.html

**Comment by RincewindsHat** [comment] 2022-01-29 15:18
I am pretty sure, this is still the case. Can we somehow reproduce this? The links are mostly dead though

**Comment by RincewindsHat** [comment] 2023-02-19 13:20
Closing this because this is too old and I don't see a good way to reproduce it.

**Closed by RincewindsHat** 2023-02-19 13:20 UTC
Labels: import, bug, argument-proccessing, debian
