### ISSUE TITLE
check_http: Unchunking body fails when no body is present

### ISSUE THREAD

**Issue by AiYoriAoshi** [monitoring-plugins/monitoring-plugins#1872] opened 2023-04-18 09:14 UTC
Checks with -N / --no-body fail with 2.3.3 

```
# /usr/local/nagios/libexec/check_http -I <IP> -4 -N -v
GET / HTTP/1.0
User-Agent: check_http/v2.3.3 (monitoring-plugins 2.3.3)
Connection: close


http://<IP>:80/ is 1460 characters
STATUS: HTTP/1.1 200 OK
**** HEADER ****
Cache-Control: must-revalidate,public
Last-Modified: Tue, 18 Apr 2023  08:44:27 GMT
Content-Type: text/html
Transfer-Encoding: chunked
Connection: Keep-Alive
**** CONTENT ****
  [[ skipped ]]
Found chunked content
Chunked content did not start with a number at all (Line: 1415)
HTTP UNKNOWN: Failed to unchunk message body
```

as mentioned in [1815](https://github.com/monitoring-plugins/monitoring-plugins/pull/1815#issuecomment-1422904273)

Adding `!no_body` to the `if` as suggested fixes the problem for me.

**Comment by mike1356** [comment] 2023-04-27 12:06
Adding !no_body to the if at line 1281 fixes it for me as well.

# /opt/plugins/check_http -H <IP> -p <port> -u /api/v1/health -N -v
GET /api/v1/health HTTP/1.1
User-Agent: check_http/v2.3git (monitoring-plugins 2.3git)
Connection: close
Host: <IP>:<port>

http://<IP>:<port>/api/v1/health is 128 characters
STATUS: HTTP/1.1 200 OK
**** HEADER ****
Server: Monkey/1.7.0
Date: Thu, 27 Apr 2023 11:59:14 GMT
Connection: Close
Transfer-Encoding: chunked
**** CONTENT ****
  [[ skipped ]]
HTTP OK: HTTP/1.1 200 OK - 128 bytes in 0.002 second response time |time=0.002058s;;;0.000000;10.000000 size=128B;;;0;

**Comment by moschlar** [comment] 2023-06-09 10:57
It seems to me that the server is sending:
`Transfer-Encoding: chunked` but no `Content-Length: 0`.

(The server being IIS...)

**Comment by trickert76** [comment] 2023-08-08 08:12
The problem is, that the parameter -N (--no-body) removes any kind of response after the header, but this [commit](https://github.com/monitoring-plugins/monitoring-plugins/commit/afe92468a54ec44cdda35e46a1eabd0d0de78840) seven months ago only reads the body and doesnt check, if the parameter --no-body is present.

**Comment by trickert76** [comment] 2023-08-08 08:19
So, this is not a bug from the HTTP server (in my case an nginx). Its a bug in the way the new code for chunked content is handling requests when --no-body is defined. There is already a fix documented but not merged.

**Comment by juliogonzalez** [comment] 2023-09-14 20:36
@trickert76 your patch seems to fix the issue for me. Thanks!

Maybe you should prepare a PR against https://github.com/monitoring-plugins/monitoring-plugins?

https://github.com/monitoring-plugins/monitoring-plugins/pull/1806 suggest that maybe `check_http` will be removed and it's mention that maybe new features should not be affected, but bugfixing should be OK.

**Comment by waja** [comment] 2023-09-15 09:07
This should be fixed with #1901, isn't it?

**Comment by RincewindsHat** [comment] 2023-09-15 09:13
@waja I think it is, but I am not completely sure, that everything is handled correctly if the server sends an empty body and `nobody` is not chosen.

**Comment by waja** [comment] 2023-09-15 09:21
> @trickert76 your patch seems to fix the issue for me. Thanks!
> 
> Maybe you should prepare a PR against https://github.com/monitoring-plugins/monitoring-plugins?
> 
> #1806 suggest that maybe `check_http` will be removed and it's mention that maybe new features should not be affected, but bugfixing should be OK.

https://github.com/monitoring-plugins/monitoring-plugins/pull/1901/commits/a6802bd5f50a5c12ed5bafa4fe9ee14fede7c1e1 is exactly what https://github.com/monitoring-plugins/monitoring-plugins/pull/1815#issuecomment-1422904273 is suggesting. So is thats the only change that is needed, we don't need another PR.

Can anybody having this issue testing `master` (which has a6802bd5f50a5c12ed5bafa4fe9ee14fede7c1e1 merged) and verify if the issue is done? thanks!

**Comment by juliogonzalez** [comment] 2023-10-04 22:50
@waja, I just built the code from `master` an uploaded `check_http` to my checkmk instance.

It works fine after forcing a first check, but since the problem was not happening all the time in the past (at least in my case), please leave me some time to confirm if it's fixed.

**Comment by juliogonzalez** [comment] 2023-10-11 18:33
@waja, after a few days, it works for me.

So FMPOV, the bug report can be closed as solved.

Thanks a lot!

**Closed** 2023-10-11 18:35 UTC
Labels: check_http
