### ISSUE TITLE
check_dns inconsistent results on Ubuntu 18.04

### ISSUE THREAD

**Issue by kenmarsh8** [monitoring-plugins/monitoring-plugins#1610] opened 2019-11-15 20:36 UTC
**Server**
cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"

/usr/lib/nagios/plugins/check_dns -V
check_dns v2.2 (monitoring-plugins 2.2)

dpkg-query -S /usr/lib/nagios/plugins/check_dns
monitoring-plugins-standard: /usr/lib/nagios/plugins/check_dns

ii  monitoring-plugins-standard           2.2-3ubuntu2                      amd64        Plugins for nagios compatible monitoring systems (standard)

uname -a
Linux hostname 4.15.0-66-generic #75-Ubuntu SMP Tue Oct 1 05:24:09 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Host1:**
dig  www.google.com @localhost +short
forcesafesearch.google.com.
216.239.38.120

/usr/lib/nagios/plugins/check_dns -s localhost -H www.google.com -a 216.239.38.120
DNS CRITICAL - expected '216.239.38.120' but got ''

**HOST2:**
/usr/lib/nagios/plugins/check_dns -s 10.1.1.1 -H www.google.com -a 172.217.7.196
CRITICAL - Plugin timed out while executing system call

dig www.google.com @10.1.1.1 +short
172.217.7.196

**Comment by ghciv6** [comment] 2020-04-14 17:16
check_dns is using nslookup for testing. can you run the plugin with "-v" to get the output of nslookup too?

**Comment by ghstwhl** [comment] 2020-05-20 09:14
I encountered a similar issue this evening when a puppet bug knocked my bind9 servers running on ubuntu 18.04 offline.  Things started breaking, but Nagios showed my name servers running fine.  These checks were running on the nagios server itself, remotely against the DNS servers.  My version of monitoring-plugins is:

```
monitoring-plugins                     2.2-3ubuntu2
monitoring-plugins-basic               2.2-3ubuntu2
monitoring-plugins-common              2.2-3ubuntu2
```

bind service running:
```
# /usr/lib/nagios/plugins/check_dns -H www.ghostwheel.com -s ns2.ghostwheel.com
DNS OK: 0.011 seconds response time. www.ghostwheel.com returns 38.99.95.53|time=0.010614s;;;0.000000
```

bind service stopped:
```
root@p7:~# /usr/lib/nagios/plugins/check_dns -H www.ghostwheel.com -s ns2.ghostwheel.com
DNS OK: 0.010 seconds response time. www.ghostwheel.com returns |time=0.009621s;;;0.000000
```

Note that in the second example there is nothing after returns, so it failed to get a response at all, and yet the status is OK.

**Comment by ghciv6** [comment] 2020-05-20 20:01
The timing makes the difference. 

My dns service is down.
`time /usr/bin/nslookup -sil www.ghostwheel.com 10.0.1.11`

runs 20-21 seconds in my environment. I have firewall rules preventing icmp port unreachable packets to arive on the monitoring host. So it gets this long timeout.

if nslokup is still running while the plugin raises it's timeout, you will get:
```
./plugins/check_dns -H www.ghostwheel.com -s 10.0.1.11 -t 15
CRITICAL - Plugin timed out while executing system call
```

if nslookup finishes, the plugin will produce the wrong state:
```
./plugins/check_dns -H www.ghostwheel.com -s 10.0.1.11 -t 25
DNS OK: 20.010 seconds response time. www.ghostwheel.com returns |time=20.010256s;;;0.000000

```

**Comment by ghciv6** [comment] 2020-05-20 20:54
@ghstwhl
you did not test against an expected address. So the returned adresses are not
compared at all. you should add "-a 38.99.95.53" to your test.

the output of nslookup changed over the time and check_dns was not able to
detect an unresponsive server in the output. i'll add a fix for this.

**Comment by ghciv6** [comment] 2020-05-20 21:16
@kenmarsh8
the cause of your issue is an unresponsive dns service. if nslookup is running
longer than 10 seconds (or the related seconds given by -t) there is no
output to parse. the plugin will output
`CRITICAL - Plugin timed out while executing system call`

if the nslookup finished before check_dns reached it's timeout, there is an
output und the plugin is able to give same hints. In your case nslookup did not
receive an answer from the dns server, but check_dns was unable to detect this
problem. You got:
`DNS CRITICAL - expected '216.239.38.120' but got ''
`
if my PR is accepted, the new output in the case is:
`No response from DNS localhost`

You will still get two different output lines for two different situations.

**Closed** 2020-05-20 21:30 UTC
