### ISSUE TITLE
check_imap doesn't support STARTTLS

### ISSUE THREAD

**Issue by peikk0** [monitoring-plugins/monitoring-plugins#1400] opened 2016-01-04 11:56 UTC
IMAPS is deprecated nowadays, STARTTLS is widely used instead, and check_imap doesn't support it.

**Comment by peikk0** [comment] 2016-01-04 12:09
Same goes with check_pop and check_jabber, as they are all symlinked to check_tcp.

**Comment by RincewindsHat** [comment] 2022-01-29 14:19
Kind of a duplicate of #1282 . Closing this to reduce the clutter

**Closed by RincewindsHat** 2022-01-29 14:19 UTC
Labels: duplicate, check_tcp
