### ISSUE TITLE
check_disk returns value inode=-1

### ISSUE THREAD

**Issue by xbujanx** [monitoring-plugins/monitoring-plugins#1599] opened 2019-06-12 12:44 UTC
I have issue with check disk on ceph filesystem, this plugins returns value inode is -1. When i run `df -i`:
```
udev                                    503377    312  503065    1% /dev
tmpfs                                   506305    572  505733    1% /run
/dev/vda5                               312624  86452  226172   28% /
tmpfs                                   506305      1  506304    1% /dev/shm
tmpfs                                   506305      4  506301    1% /run/lock
tmpfs                                   506305     15  506290    1% /sys/fs/cgroup
/dev/vda1                                60720    345   60375    1% /boot
/dev/vdc                                131072   3722  127350    3% /var
/dev/vdb                                 65536     69   65467    1% /home
/dev/vdd                               2621440 149352 2472088    6% /var/lib/docker
10.0.0.2,10.0.0.3,10.0.0.4:/  204972      -       -     - /data
```
And check_disk returns:
```
/usr/lib/nagios/plugins/check_disk -w 15% -c 10% -p /data
DISK OK - free space: /data 8542956 MB (85% inode=-1%);| /data=1449488MB;8493577;8993199;0;9992444
```
Can I disable chek inode for specific fs/mountpoint?

**Comment by RincewindsHat** [comment] 2021-11-01 17:31
Well, the check is actually disabled, therefore the `DISK OK`, but yes, you can exclude certain types of filesystems ( `-X` )

**Comment by RincewindsHat** [comment] 2022-01-29 13:10
@xbujanx What kind of file system is `/data`? NFS? Is so, I can not reproduce this spontaneously.
How does it look like with the current `master`?
If the topic has solved itself, I would like to close this issue

**Comment by RincewindsHat** [comment] 2022-07-27 20:55
Closing this if there is no objection, since I cannot reproduce this

**Closed by RincewindsHat** 2022-07-27 20:55 UTC
Labels: waiting for feedback, check_disk
