### ISSUE TITLE
check_http segfaults with TLS enabled in some cases

### ISSUE THREAD

**Issue by C0rn3j** [monitoring-plugins/monitoring-plugins#1905] opened 2023-08-26 22:31 UTC
`check_http v2.3.3 (monitoring-plugins 2.3.3)`

```console
% '/usr/lib/monitoring-plugins/check_http' '--hostname=mail.rys.pw'             
HTTP OK: HTTP/1.1 301 Moved Permanently - 432 bytes in 0.058 second response time |time=0.057549s;;;0.000000;10.000000 size=432B;;;0;

% '/usr/lib/monitoring-plugins/check_http' '--hostname=mail.rys.pw' '--ssl=1.2+'          
[1]    564577 segmentation fault (core dumped)  '/usr/lib/monitoring-plugins/check_http' '--hostname=mail.rys.pw' '--ssl=1.2+
```

Here's a curl check against the same URL (missing from example above, but it behaves the same on `/` and `/login.php`)

```console
[0] % curl -v https://mail.rys.pw/login.php
* processing: https://mail.rys.pw/login.php
*   Trying 51.15.117.74:443...
* Connected to mail.rys.pw (51.15.117.74) port 443
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=mail.rys.pw
*  start date: Jul 28 15:03:30 2023 GMT
*  expire date: Oct 26 15:03:29 2023 GMT
*  subjectAltName: host "mail.rys.pw" matched cert's "mail.rys.pw"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* using HTTP/2
* h2 [:method: GET]
* h2 [:scheme: https]
* h2 [:authority: mail.rys.pw]
* h2 [:path: /login.php]
* h2 [user-agent: curl/8.2.1]
* h2 [accept: */*]
* Using Stream ID: 1
> GET /login.php HTTP/2
> Host: mail.rys.pw
> User-Agent: curl/8.2.1
> Accept: */*
> 
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 500 
< server: nginx/1.24.0
< date: Sat, 26 Aug 2023 22:29:23 GMT
< content-type: text/html; charset=UTF-8
< x-powered-by: PHP/8.2.9
< set-cookie: postfixadmin_session=n1avmg867q9mc2umaocui3hstd; path=/
< expires: Thu, 19 Nov 1981 08:52:00 GMT
< cache-control: no-store, no-cache, must-revalidate
< pragma: no-cache
< x-frame-options: DENY
< 
* Connection #0 to host mail.rys.pw left intact
```

**Comment by RincewindsHat** [comment] 2023-08-26 22:32
Hi, does it work with `check_curl`?

**Comment by C0rn3j** [comment] 2023-08-26 22:36
`check_curl` does not look like an executable monitoring-plugins provides?

I am using Arch Linux and [can't see anything out of the ordinary](https://gitlab.archlinux.org/archlinux/packaging/packages/monitoring-plugins/-/blob/main/PKGBUILD?ref_type=heads) that would prevent it from being present... 

The host is up at the moment with the same issue (it's throwing error 500, which I'm trying to fix and somewhat suspect is the reason this segfault happens) so you could test again it yourself if need be.

**Comment by RincewindsHat** [comment] 2023-08-26 22:43
ahhh, I see. In general the usage of `check_http` should be replaced with `check_curl`, the former one is getting deprecated.

**Comment by C0rn3j** [comment] 2023-08-26 22:50
```
% '/usr/lib/monitoring-plugins/check_curl' '--hostname=mail.rys.pw' '--ssl=1.2+' '--string=login here' '--url=/login.php'

HTTP CRITICAL - Invalid HTTP response received from host on port 443: cURL returned 7 - Failed to connect to mail.rys.pw port 443 after 0 ms: Couldn't connect to server
```

`check_curl` returns this with the same parameters, which is probably correct as the server it is checking against currently sends error code 500 back.

**Comment by RincewindsHat** [comment] 2023-10-09 15:20
Hi @C0rn3j can this still be reproduced?

**Comment by C0rn3j** [comment] 2023-10-09 17:54
Yes.
```
[0] % '/usr/lib/monitoring-plugins/check_http' '--hostname=mail.rys.pw' '--ssl=1.2+' 
[1]    1202338 segmentation fault (core dumped)  '/usr/lib/monitoring-plugins/check_http' '--hostname=mail.rys.pw' '--ssl=1.2+
```

I've migrated my checks to `check_curl` in the meanwhile to work around this issue.

Or do you mean against git master?

**Comment by RincewindsHat** [comment] 2023-10-09 17:58
hm, funny, works for me (does not segfault) on debian stable and testing and git master versions.
what's your OS? some funny `libc` or tls lib on there?

could you try with the `master` branch? just to satisfy my curiosity

**Comment by C0rn3j** [comment] 2023-10-09 19:09
Arch Linux.

I can reproduce on an LXD Arch container.

I can't reproduce on Ubuntu 22.04 LXD container.

I'll see about testing master later

**Comment by C0rn3j** [comment] 2023-10-09 21:00
I compiled the same problematic package build script on my system, same issue.

I merely bumped the source to master, and the problem is gone, so I presume a random commit in the last months fixed it and it just needs a release.

**Comment by RincewindsHat** [comment] 2023-10-10 05:51
hm, not entirely satisfying, but at least it is fixed.
Thank you very much for your time.
I will close this issue now, since it seems to be fixed.

**Closed by RincewindsHat** 2023-10-10 05:51 UTC
Labels: bug, check_http
