### ISSUE TITLE
check_snmp: performance data includes warning/critical thresholds wrong w/ multiple OIDS

### ISSUE THREAD

**Issue by s3ta** [monitoring-plugins/monitoring-plugins#1327] opened 2015-03-10 15:08 UTC
Refering to the NEWS:
2.2 [...]
    ENHANCEMENTS
    check_snmp's performance data now also includes warning/critical thresholds

I tried that, since I am waiting for the feature.

My tests / example for a Switch port ( w/ current git-version check_snmp v2.1.1.39.g8095 (monitoring-plugins 2.1.1)) looked like this:
```
 /usr/local/libexec/check_snmp -H 192.168.2.1 --rate -C public-P 2c -o ifInOctets.1,ifOutOctets.1,ifInUcastPkts.1,ifOutUcastPkts.1,ifInErrors.1,ifOutErrors.1 -m IF-MIB -l in,out,inucast,outucast,inerr,outerr -w 230400,230400,1000000000,1000000000,0.01,0.01 -c 230400,230400,1000000000,1000000000,0.01,0.01
SNMP RATE OK - in 8273.875 out 31296.25 inucast 92.125 outucast 64.5 inerr 0 outerr 0 | in=8273.875;230400,230400,1000000000,1000000000,0.01,0.01;230400,230400,1000000000,1000000000,0.01,0.01 out=31296.25;230400,230400,1000000000,1000000000,0.01,0.01;230400,230400,1000000000,1000000000,0.01,0.01 inucast=92.125;230400,230400,1000000000,1000000000,0.01,0.01;230400,230400,1000000000,1000000000,0.01,0.01 outucast=64.5;230400,230400,1000000000,1000000000,0.01,0.01;230400,230400,1000000000,1000000000,0.01,0.01 inerr=0;230400,230400,1000000000,1000000000,0.01,0.01;230400,230400,1000000000,1000000000,0.01,0.01 outerr=0;230400,230400,1000000000,1000000000,0.01,0.01;230400,230400,1000000000,1000000000,0.01,0.01
```
The warning/critical values included in the perfdata are the complete strings of -w / -c - not just the (parsed?) value used for the check against it.

For the sake of understanding correctly, I expected as result:
```
SNMP RATE OK - in 8273.875 out 31296.25 inucast 92.125 outucast 64.5 inerr 0 outerr 0 | in=8273.875;230400;230400 out=31296.25;230400;230400 inucast=92.125;1000000000;1000000000 outucast=64.5;1000000000;1000000000 inerr=0;0.01;0.01 outerr=0;0.01;0.01
```

**Comment by chuhn** [comment] 2021-01-17 11:14
Is [this](https://github.com/nagios-plugins/nagios-plugins/issues/291#issuecomment-329992594) the fix required here?

Seems to be the same issue.

**Comment by mitch-geht-ab** [comment] 2021-08-23 08:18
Hi,
this problem seems more important since icinga2 2.13 (not with 2.12) has a problem to import perfdata to influx with multiple warn/crit per metric.
icinga2 itself has no problem with it, but the import module:

```
'/usr/lib/nagios/plugins/check_snmp' '-C' 'xxxxxxx' '-H' '192.168.yyyyy' '-c' '45,60000:' '-l' 'Temperature,Remaining' '-o' '.1.3.6.1.4.1.318.1.1.1.2.2.2.0,.1.3.6.1.4.1.318.1.1.1.2.2.3.0' '-t' '12' '-u' 'C,Millisec' '-w' '38,84000:'
SNMP OK - Temperature 36 C Remaining 150000 Millisec | Temperature=36;38,84000:;45,60000: Remaining=150000;38,84000:;45,60000:

### from: /var/log/icinga2/icinga2.log:

[2021-08-23 06:17:47 +0200] warning/InfluxdbWriter: Ignoring invalid perfdata for checkable 'usv.dthree.de!snmpv1-usv-status' and command 'snmp' with value: Temperature=36;38,84000:;45,60000:
Context:
        (0) Processing check result for 'usv.dthree.de!snmpv1-usv-status'
```

```
lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

ii  monitoring-plugins                    2.3.1-1~bpo10+1                                 all          Plugins for nagios compatible monitoring systems (metapackage)
ii  monitoring-plugins-basic              2.3.1-1~bpo10+1                                 amd64        Plugins for nagios compatible monitoring systems (basic)
ii  monitoring-plugins-common             2.3.1-1~bpo10+1                                 amd64        Common files for plugins for nagios compatible monitoring
ii  monitoring-plugins-standard           2.3.1-1~bpo10+1                                 amd64        Plugins for nagios compatible monitoring systems (standard)

/usr/lib/nagios/plugins/check_snmp -h|head
check_snmp v2.3.1 (monitoring-plugins 2.3.1)
Copyright (c) 1999-2007 Monitoring Plugins Development Team
        <devel@monitoring-plugins.org>
```

Problem since icinga2 update    "icinga2-bin:amd64 (2.12.5-1.buster, 2.13.0-1.buster)"

**Comment by mitch-geht-ab** [comment] 2021-10-03 07:05
Hello,
is there any progress?
In the meantime I tested Nagios Plugins 2.3.3 and the [fix ](https://github.com/nagios-plugins/nagios-plugins/issues/291#issuecomment-329992594) @chuhn mentioned [here](https://github.com/monitoring-plugins/monitoring-plugins/issues/1327#issuecomment-761773396) solves the problem.

BR
mitch

**Comment by RincewindsHat** [comment] 2022-07-24 16:11
Hi @mitch-geht-ab  @s3ta 
Could you try this with the current master? I can not reproduce it, seems to look fine.
I am closing this issue therefore, pls reopen if this is still happening

**Closed by RincewindsHat** 2022-07-24 16:11 UTC
Labels: bug, squash, check_snmp

**Comment by mitch-geht-ab** [comment] 2022-09-18 10:58
sorry for reopen it, but don't want to leave it uncommented.
yes it work's, as expected with master branch.

```
check_snmp --version
check_snmp v2.3.202.gb89a (monitoring-plugins 2.3git)

check_snmp '-C' 'xxxxxxxxxx' '-H' 'yyyyyyyyyy' '-c' '45,60000:' '-l' 'Temperature,Remaining' '-o' '.1.3.6.1.4.1.318.1.1.1.2.2.2.0,.1.3.6.1.4.1.318.1.1.1.2.2.3.0' '-t' '12' '-u' 'C,Millisec' '-w' '38,84000:'
SNMP OK - Temperature 35 C Remaining 144000 Millisec | Temperature=35;38;45 Remaining=144000;84000:;60000:
```

BR
mitch
