### ISSUE TITLE
check_snmp: offset

### ISSUE THREAD

**Issue by lnxbil** [monitoring-plugins/monitoring-plugins#1306] opened 2014-12-15 11:07 UTC
Hi,

I'm trying to subtract something from the given value, but it does not work. Maybe I do not understand it correctly, but have a look:

<pre>
$ ./check_snmp --version
check_snmp v2.1.1.37.g8235 (monitoring-plugins 2.1.1)

$ ./check_snmp -o IF-MIB::ifSpeed.1 --offset=-999900.0 -u MBit -m RFC1213-MIB -l Speed switch
SNMP OK - Speed 100000000 MBit | Speed=100000000 

$ ./check_snmp -o IF-MIB::ifSpeed.1 --offset=999900.0 -u MBit -m RFC1213-MIB -l Speed switch
SNMP OK - Speed 100000000 MBit | Speed=100000000 

$ ./check_snmp -o IF-MIB::ifSpeed.1 --offset=999900 -u MBit -m RFC1213-MIB -l Speed switch
SNMP OK - Speed 100000000 MBit | Speed=100000000 

$ ./check_snmp -o IF-MIB::ifSpeed.1 --offset -999900 -u MBit -m RFC1213-MIB -l Speed switch
SNMP OK - Speed 100000000 MBit | Speed=100000000 
</pre>

**Comment by RincewindsHat** [comment] 2021-11-28 13:24
Just a speculation, but this might be a problem with the datatype of the result, but I don't have device at hand, which I could use to test this.
Could you confirm that the problem is still existent and maybe add a `-vvv` output to this issue?

**Comment by RincewindsHat** [comment] 2023-09-04 21:36
Closing this since we don't know whether there is a problem and it still exists.

**Closed by RincewindsHat** 2023-09-04 21:36 UTC
Labels: bug, waiting for feedback, squash, check_snmp

**Comment by lnxbil** [comment] 2023-09-05 06:31
Sorry, I don't know either if the problem still exists, I don't have the hardware anymore from almost 10 years ago.
