### ISSUE TITLE
check_disk --local tries to check cifs mount on Arch Linux

### ISSUE THREAD

**Issue by Dr-Bone** [monitoring-plugins/monitoring-plugins#1653] opened 2020-12-30 16:42 UTC
Arch Linux
$ uname -r
5.9.14-arch1-1x
$ check_disk --version
check_disk v2.2 (monitoring-plugins 2.2)

$ /usr/lib/monitoring-plugins/check_disk --local -w 10% -c 5%
DISK CRITICAL - /home/someuser/some/path is not accessible: Keine Berechtigung 
("Keine Berechtigung" is german for "access denied")

However this path is actually a cifs mount, the fstab entry for it (censored as above) is:
//server.domain/share /home/someuser/some/path cifs credentials=/path/file,uid=1234,gid=1234,_netdev,noauto,nofail,x-systemd.automount,x-systemd.idle-timeout=1min,x-systemd.mount-timeout=10,user 0 2

This might be related/the same issue as
https://github.com/monitoring-plugins/monitoring-plugins/issues/803

**Comment by ghciv6** [comment] 2021-01-12 19:40
... or it is related to #1622 

what is the UID who starts check_disk and what are the permissions for /home/someuser/some and /home/someuser/some/path ?

**Comment by Dr-Bone** [comment] 2021-01-13 08:19
the user starting the check is "sensu" (without sudo) UID>1000
the users who are having cifs mounts in their homes UID>1000
the user sensu does not have permission to list or read on the home directories of those users 

However I'm missing the reason why this should matter, I'm sorry. As it is a cifs mount and should not be looked at anyways when I specify to only check local mounts, or am I missing something here?

**Comment by ghciv6** [comment] 2021-01-17 20:03
i can't reproduce it in CentOS7. are you able to reproduce it on arch linux with the current master branch?

**Comment by ghciv6** [comment] 2021-01-17 21:35
i can't reproduce the issue with Arch Linux 5.10.7, latest check_disk running as root and cifs filesystem mounted on /mnt

```
./plugins/check_disk
DISK OK - free space: /dev 983 MB (100% inode=99%); /run 990 MB (99% inode=99%); / 15622 MB (86% inode=95%);/dev/shm 990 MB (100% inode=99%); /sys/fs/cgroup 4 MB (100% inode=98%); /tmp 990 MB (99% inode=99%); /run/user/0 198 MB (100% inode=99%); /mnt 16 MB (83% inode=-);| /dev=0MB;;;0;983 /run=0MB;;;0;990 /=2410MB;;;0;19021 /dev/shm=0MB;;;0;990 /sys/fs/cgroup=0MB;;;0;4 /tmp=0MB;;;0;990 /run/user/0=0MB;;;0;198 /mnt=3MB;;;0;20

``` 

```
./plugins/check_disk --local
DISK OK - free space: /dev 983 MB (100% inode=99%); /run 990 MB (99% inode=99%); / 15622 MB (86% inode=95%); /dev/shm 990 MB (100% inode=99%); /sys/fs/cgroup 4 MB (100% inode=98%); /tmp 990 MB (99% inode=99%); /run/user/0 198 MB (100% inode=99%);| /dev=0MB;;;0;983 /run=0MB;;;0;990 /=2410MB;;;0;19021 /dev/shm=0MB;;;0;990 /sys/fs/cgroup=0MB;;;0;4 /tmp=0MB;;;0;990 /run/user/0=0MB;;;0;198
```

**Comment by ghciv6** [comment] 2021-02-12 08:57
if you have no additional information, please consider to close this issue.

**Closed** 2021-02-12 08:58 UTC
